sudo: required
services:
  - docker

before_install:
  - docker build -t eikkon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  eikkon/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "test1"
  env: "test1-env"
  bucket_name: "elasticbeanstalk-eu-north-1-953823691034"
  bucket_path: "test1"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"